export const SIDEBAR_VISIBILITY = 'SIDEBAR_VISIBILITY'
export const BUTTON_SIDEBAR_VISIBILITY = 'BUTTON_SIDEBAR_VISIBILITY'
export const GROUPS_LIST = 'GROUPS_LIST'
export const FILTER_GROUP = 'FILTER_GROUP'

