export const SIDEBAR_VISIBILITY = 'SIDEBAR_VISIBILITY'
export const BUTTON_SIDEBAR_VISIBILITY = 'BUTTON_SIDEBAR_VISIBILITY'
export const MENU_VISIBILITY = 'MENU_VISIBILITY'
export const FILTER_GROUP = 'FILTER_GROUP'
export const FETCH_GROUPS = 'FETCH_GROUPS'
export const SIDEBAR_ITEMS = 'SIDEBAR_ITEMS'
export const ACTIVE_GROUP_DATA = 'ACTIVE_GROUP_DATA'

